apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceclient.admiral.io
spec:
  group: admiral.io
  version: v1alpha1
  names:
    kind: ServiceClient
    plural: serviceclients
  scope: Namespaced